import { useState } from "react";

type StaticDevice = {
  name: string;
  mac: string;
  ip: string;
};

export default function RouterSetup() {
  const [ssid, setSsid] = useState("TX-SCARA");
  const [wifiPassword, setWifiPassword] = useState("");
  const routerIp = "192.168.200.1";
  const [pcIp, setPcIp] = useState("192.168.200.10");
  const [prefixLength, setPrefixLength] = useState("24");
  const [gateway, setGateway] = useState("192.168.200.1");
  const [dns1, setDns1] = useState("8.8.8.8");
  const [dns2, setDns2] = useState("1.1.1.1");
  const [dhcpStart, setDhcpStart] = useState("192.168.200.100");
  const [dhcpEnd, setDhcpEnd] = useState("192.168.200.199");
  const [interfaceName, setInterfaceName] = useState("Wi-Fi");
  const [devices, setDevices] = useState<StaticDevice[]>([
    { name: "Robot", mac: "", ip: "192.168.200.8" },
    { name: "PICO", mac: "", ip: "192.168.200.90" },
    { name: "Front Cam / FC", mac: "", ip: "192.168.200.60" },
    { name: "Back Cam / BC", mac: "", ip: "192.168.200.61" },
  ]);

  const updateDevice = (index: number, key: keyof StaticDevice, value: string) => {
    setDevices((prev) => prev.map((d, i) => (i === index ? { ...d, [key]: value } : d)));
  };

  const addDevice = () => {
    setDevices((prev) => [...prev, { name: "", mac: "", ip: "" }]);
  };

  const removeDevice = (index: number) => {
    setDevices((prev) => prev.filter((_, i) => i !== index));
  };

  const settingText = `SSID: ${ssid}
Wi-Fi Password: ${wifiPassword}
Router IP: ${routerIp}
PC Fixed IP: ${pcIp}
Prefix Length: ${prefixLength}
Gateway: ${gateway}
DNS: ${dns1}, ${dns2}
DHCP Range: ${dhcpStart} - ${dhcpEnd}

Static IP Devices:
${devices.map((d) => `- ${d.name || "(no name)"} / MAC: ${d.mac || "(empty)"} / IP: ${d.ip || "(empty)"}`).join("\n")}
`;

  const generatePowerShell = () => {
    const deviceNotes = devices
      .map((d) => `# ${d.name || "Device"} | MAC: ${d.mac || "-"} | Fixed IP: ${d.ip || "-"}`)
      .join("\r\n");

    return `# TP-Link Router Setup Helper
# Generated by Telexistence Guide
# Run PowerShell as Administrator.

$ErrorActionPreference = "Stop"

$InterfaceName = "${interfaceName}"
$IPAddress = "${pcIp}"
$PrefixLength = ${Number(prefixLength) || 24}
$Gateway = "${gateway}"
$DnsServers = @("${dns1}", "${dns2}")
$RouterUrl = "http://${routerIp}"

Write-Host "=== TP-Link Router Setup Helper ===" -ForegroundColor Cyan
Write-Host "Interface: $InterfaceName"
Write-Host "PC IP: $IPAddress"
Write-Host "Gateway: $Gateway"
Write-Host ""

Write-Host "Removing old IPv4 addresses..." -ForegroundColor Yellow
Get-NetIPAddress -InterfaceAlias $InterfaceName -AddressFamily IPv4 -ErrorAction SilentlyContinue |
  Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue

Write-Host "Removing old default routes..." -ForegroundColor Yellow
Get-NetRoute -InterfaceAlias $InterfaceName -AddressFamily IPv4 -ErrorAction SilentlyContinue |
  Where-Object { $_.DestinationPrefix -eq "0.0.0.0/0" } |
  Remove-NetRoute -Confirm:$false -ErrorAction SilentlyContinue

Write-Host "Applying fixed IP..." -ForegroundColor Yellow
New-NetIPAddress -InterfaceAlias $InterfaceName -IPAddress $IPAddress -PrefixLength $PrefixLength -DefaultGateway $Gateway

Write-Host "Applying DNS..." -ForegroundColor Yellow
Set-DnsClientServerAddress -InterfaceAlias $InterfaceName -ServerAddresses $DnsServers

$Settings = @"
TP-Link Manual Input Values

SSID:
${ssid}

Wi-Fi Password:
${wifiPassword}

Router IP:
${routerIp}

DHCP Start:
${dhcpStart}

DHCP End:
${dhcpEnd}

Static IP Reservation:
${devices.map((d) => `${d.name || "Device"} | MAC: ${d.mac || "-"} | IP: ${d.ip || "-"}`).join("\r\n")}
"@

$Settings | Set-Clipboard

Write-Host ""
Write-Host "Settings copied to clipboard." -ForegroundColor Green
Write-Host "Opening TP-Link admin page: $RouterUrl" -ForegroundColor Green
Start-Process $RouterUrl

Write-Host ""
Write-Host "Static IP notes:" -ForegroundColor Cyan
${deviceNotes}

Write-Host ""
Write-Host "Done. Press Enter to close."
Read-Host
`;
  };

  const downloadPowerShell = () => {
    const script = generatePowerShell();
    const blob = new Blob([script], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "tplink-setup.ps1";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  };

  const copySettings = async () => {
    await navigator.clipboard.writeText(settingText);
    alert("設定値をコピーしました");
  };

  const openRouter = () => {
    window.open(`http://${routerIp}`, "_blank", "noopener,noreferrer");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="glitch-text text-3xl font-bold text-primary" data-text="Router Setup">
          Router Setup
        </h1>
        <p className="mono-sub mt-2">// TP_LINK_CONFIGURATION_HELPER</p>
      </div>

      <section className="cyber-border rounded-lg p-4 bg-card space-y-4">
        <h2 className="text-xl font-semibold text-foreground">TP-Link ルーター設定</h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">SSID</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={ssid} onChange={(e) => setSsid(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">Wi-Fi Password</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={wifiPassword} onChange={(e) => setWifiPassword(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">ルーター設定ページ</span>
            <div className="w-full px-3 py-2 rounded-md bg-muted border border-border text-foreground">
              http://192.168.200.1
            </div>
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">PC固定IP</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={pcIp} onChange={(e) => setPcIp(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">Prefix Length</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={prefixLength} onChange={(e) => setPrefixLength(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">Gateway</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={gateway} onChange={(e) => setGateway(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">DNS 1</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={dns1} onChange={(e) => setDns1(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">DNS 2</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={dns2} onChange={(e) => setDns2(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">DHCP開始IP</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={dhcpStart} onChange={(e) => setDhcpStart(e.target.value)} />
          </label>

          <label className="space-y-1">
            <span className="text-sm text-muted-foreground">DHCP終了IP</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={dhcpEnd} onChange={(e) => setDhcpEnd(e.target.value)} />
          </label>

          <label className="space-y-1 md:col-span-2">
            <span className="text-sm text-muted-foreground">PCネットワーク名</span>
            <input className="w-full px-3 py-2 rounded-md bg-input border border-border" value={interfaceName} onChange={(e) => setInterfaceName(e.target.value)} />
            <p className="text-xs text-muted-foreground">通常は Wi-Fi。LANなら Ethernet に変更。</p>
          </label>
        </div>
      </section>

      <section className="cyber-border rounded-lg p-4 bg-card space-y-3">
        <div className="flex items-center justify-between gap-3">
          <h2 className="text-xl font-semibold text-foreground">固定IPリスト</h2>
          <button onClick={addDevice} className="px-3 py-2 rounded-md bg-primary text-primary-foreground text-sm">
            + 追加
          </button>
        </div>

        <div className="space-y-2">
          {devices.map((device, index) => (
            <div key={index} className="grid grid-cols-1 md:grid-cols-[1fr_1fr_1fr_auto] gap-2">
              <input className="px-3 py-2 rounded-md bg-input border border-border" placeholder="機器名" value={device.name} onChange={(e) => updateDevice(index, "name", e.target.value)} />
              <input className="px-3 py-2 rounded-md bg-input border border-border" placeholder="MAC Address" value={device.mac} onChange={(e) => updateDevice(index, "mac", e.target.value)} />
              <input className="px-3 py-2 rounded-md bg-input border border-border" placeholder="固定IP" value={device.ip} onChange={(e) => updateDevice(index, "ip", e.target.value)} />
              <button onClick={() => removeDevice(index)} className="px-3 py-2 rounded-md border border-border text-muted-foreground hover:text-destructive">
                削除
              </button>
            </div>
          ))}
        </div>
      </section>

      <section className="cyber-border rounded-lg p-4 bg-card space-y-3">
        <h2 className="text-xl font-semibold text-foreground">実行</h2>
        <div className="flex flex-wrap gap-3">
          <button onClick={downloadPowerShell} className="px-4 py-2 rounded-md bg-primary text-primary-foreground">
            PowerShellを作成
          </button>
          <button onClick={openRouter} className="px-4 py-2 rounded-md border border-border hover:bg-muted">
            TP-Link管理画面を開く
          </button>
          <button onClick={copySettings} className="px-4 py-2 rounded-md border border-border hover:bg-muted">
            設定値をコピー
          </button>
        </div>
        <p className="text-sm text-muted-foreground">
          PowerShellはPC側の固定IPとDNSを自動設定し、TP-Link管理画面を開きます。SSIDやDHCPはコピーされた値を管理画面へ入力してください。
        </p>
      </section>
    </div>
  );
}




